### ISSUE TITLE
Hyperclick has stopped maintenance, so why rely on this plug-in?

### ISSUE THREAD

**Issue by linjialiang** [atom-ide-community/atom-ide-definitions#5]
> Hyperclick has stopped maintenance, so why rely on this plug-in?

**Comment by linjialiang** [comment]
> can also achieve the same effect with the shortcut keys.  `hyperclick` plug-ins are not required!

**Comment by Aerijo** [comment]
> can also achieve the same effect with the shortcut keys

No, you can't. You cannot bind a mouse click to a keybinding. Perhaps you are fine with purely using keybindings, but some (like myself) feel that being able to ctrl-click on a word and have it do something intuitive is a very nice feeling. Clicking to position the cursor, and then pressing a shortcut feels janky by comparison (and will move the cursor from wherever it was beforehand).

> Hyperclick has stopped maintenance, so why rely on this plug-in?

I understand it to be temporary. It makes little sense right now to write a replacement from scratch, when Hyperclick exists and does it's job to a satisfactory level. To do so would drain development time from other features, including ones that weren't implemented at all in `atom-ide-ui`.

**Comment by ryanolsonx** [comment]
Hyperclick works well. It's at a feature set that is functional and has been working for a long time. If the publisher of Hyperclick ever decides to remove it from the atom packages repo, we will fork and re-publish. For now, Hyperclick is an _optional_ dependency that gives you ctrl+click capabilities. If you don't install Hyperclick, that's totally fine -- shortcuts will work (as you mentioned).
