### ISSUE TITLE
What is a definition please?

### ISSUE THREAD

**Issue by tomachinz** [atom-ide-community/atom-ide-definitions#6]
The package description could explain what a definition is.

**Comment by ryanolsonx** [comment]
Good idea. A definition is where a symbol under your cursor was defined.

For example, if you have this code (`|` signifies where the cursor is):

```js
function goToHomePage() {
  window.location.href = "https://google.com";
}

function handleClick(e) {
  goTo|HomePage();
}
```

When you go to definition, it would take you to where that `goToHomePage` function is defined. The cursor would move to line 1. If that function was defined in another file, it could possibly go to that function there (depending on if you import that function or use it as a global).

**Comment by Belar** [comment]
As @ryanolsonx explained, definition is where target (variable, function, class etc.) has been defined. We could add a gif presenting the functionality, similar to [the one in old ide-ui package](https://github.com/facebookarchive/atom-ide-ui/blob/master/docs/definitions.md).
